name: PR Comment Test
on:
  pull_request:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Crear tfplan.json dummy
        run: |
          cat > tfplan.json <<'EOF'
          {
            "format_version": "1.2",
            "terraform_version": "1.9.0",
            "resource_changes": [
              {
                "address": "aws_s3_bucket.logs",
                "type": "aws_s3_bucket",
                "name": "logs",
                "change": { "actions": ["create"] }
              },
              {
                "address": "aws_iam_role.app",
                "type": "aws_iam_role",
                "name": "app",
                "change": { "actions": ["update"] }
              },
              {
                "address": "aws_db_instance.main",
                "type": "aws_db_instance",
                "name": "main",
                "change": {
                  "actions": ["delete", "create"],
                  "before": { "password": "LEAK_BEFORE_SUPER_SECRET_123" },
                  "after": { "password": "LEAK_AFTER_SUPER_SECRET_456" },
                  "before_sensitive": { "password": true },
                  "after_sensitive": { "password": true }
                }
              }
            ]
          }
          EOF

      - name: Ejecutar la Action (referencia local)
        uses: ./
        with:
          plan_path: tfplan.json
          pr_comment: 'true'
          github_token: ${{ github.token }}
          jira_base_url: https://terraform2jira.atlassian.net
          jira_email: ${{ secrets.JIRA_EMAIL }}
          jira_api_token: ${{ secrets.JIRA_API_TOKEN }}
          # jira_issue_key: CORE-1
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
